### ISSUE TITLE
No hyperlinks

### ISSUE THREAD

**Issue by iwob** [boazbk/tcs#247]
Hello, in Introduction at the end there is a mention of "blog post of Tao", but in my pdf viewer (Evince) it is not clickable and there is no way to get the URL. In the same way, it would be useful if the citations of the literature were inter-document hyperlinks.

**Comment by boazbk** [comment]
Thanks! I was using a too aggressive settings for acrobat pdf optimizer that destroyed all the internal and external hyperlinks.  This should be fixed soon (due to caching it might take a while for the version on the website to be updated). The citations are now hyperlinks too in the pdf for the full book (the individual parts for each chapter do not contain the bibliography).
I also improved the references and links in the web version (before I didn't have theorem numbers and no links between different chapters).
