### ISSUE TITLE
Definition of desugar (Figure 4.3)

### ISSUE THREAD

**Issue by evansuva** [boazbk/tcs#284]
Normally, I really like recursive definitions, but I think in this case it is making what this does harder to understand and more complicated than necessary. Also, would like the docstring to be the specification for the function, not describing implementation, to stick with the book theme of separating these two. I'll submit a separate PR for the tcscode repo for what I would prefer (but posting issue here also to connect to chapter).

**Comment by boazbk** [comment]
Sounds good - btw the code snippets in the actual book have a different goal than the repository. In the repository we want code that works while in the book we want to only include short snippets that illustrate the main idea.

So one possibility is that in the book there is just the function that removes a single procedure call, and then we say that we use it again and again to implement the full desugar function (which will be implemented in the repository).

The notion of “syntactic sugar” is quite important since it connects to practice and makes tangible the kind of theorems that are the “bread and butter” of such a course: showing that computational model A can simulate model B

**Comment by boazbk** [comment]
Edited it to a non recursive definition
