### ISSUE TITLE
Definition 4.17, s >= m

### ISSUE THREAD

**Issue by evansuva** [boazbk/tcs#286]
I think the constraint that s >= m for the definition of SIZE is unnecessary - if s < m, the set is still defined and non-empty, just limited to functions where an output bit is fixed. This is kind of similar to the (not included) constraint s >= n. SIZE is well defined for s < n, but it only includes functions where some inputs are totally ignored. I could see a case for including both constraints (s >= n, s >= m), but don't see a case for just including s >= m (and seems best to just allow the definition for any n, m, s even though the functions in SIZE for n < s and m < s are "silly" functions.

**Comment by rxu18** [comment]
To push back, I think keeping the constraint of s >= m fits better with the rest of the text. This is because
1. In the NAND-CIRC program examples we end our programs with Y[i]=j statements. And, the examples always computed 0 and 1 instead of assuming an initial value. Dropping the condition can leave students confused.
2. There is an interesting use case for functions with s<n. We define size and time in terms of length of the input. In the runtime lectures, sometimes we pad the input with 1^n so that the problem "show this function is in P" has an interesting answer. However, functions with s<m are just uninteresting.

**Comment by evansuva** [comment]
Just to push back on 2, I think we've already used two "interesting" functions with s<m: the constant ZERO and ONE functions (I'd have to look more carefully at the definitions to be sure these can be implemented with 0 gates).

**Comment by evansuva** [comment]
Actually, I'm wrong...take back the previous comment. You do need gates to implement ZERO and ONE.

**Comment by boazbk** [comment]
That is a good question. I like the constraint s >= m (and maybe add s >= n too) since the class SIZE is supposed to correspond to Boolean circuits, and usually in circuits we can't have more inputs or outputs than gates.  Have to think what's the most elegant way to do it, maybe we should add s>=n too. 

The important thing is to keep the equivalence between circuits and straightline programs so that the SIZE class is the same regardless if it is defined using the former or the latter

**Comment by boazbk** [comment]
At the moment closing this issue, but let me know if some lessons from teaching favor making the decision one way or the other
