### ISSUE TITLE
Typos in Chapter 3: Defining Computation

### ISSUE THREAD

**Issue by dzhou22** [boazbk/tcs#317]
**Chapter name**: Defining Computation

**List of bugs/typos**

1. In **Equivalence of circuits and straight-line programs**, in the *Solved Exercise*, I think the solution should be:
```python
temp_1 = NOT(X[2]) #NOT(c)
temp_2 = AND(X[0],temp_1)  #(a > c)
temp_3 = NOT(X[0]) #NOT(a)
temp_4 = OR(X[2],temp_3) #NOT (c < a)
temp_5 = NOT(X[3]) #NOT(d)
temp_6 = AND(X[1],temp_5) #(b > d)
temp_7 = AND(temp_6,temp_4) #(b>d) AND (NOT(c<a))
Y[0] = OR(temp_2,temp_7) #(a>c) OR ((b>d) AND (NOT(c<a)))
```
Currently it says:
```python
temp_1 = NOT(X[2])
temp_2 = OR(X[0],temp_1)
temp_3 = NOT(X[0])
temp_4 = OR(X[2],temp_3)
temp_5 = NOT(X[3])
temp_6 = OR(X[1],temp_5)
temp_7 = AND(temp_6,temp_4)
Y[0] = OR(temp_2,temp_7)
```
Hopefully I have understood this correctly. If not, please ignore this.

**Comment by rxu18** [comment]
Thanks! I'll read it over. Working on it rn.

**Comment by rxu18** [comment]
@dzhou22 are you proposing that we add comments to the code to explain it? I think that's a great idea in general, but the comment you put seem to describe the program verbatim and further complicates the program. What do you think?

**Comment by dzhou22** [comment]
No, I wrote the comments to explain what each line was in case each operation wasn't clear for you to check, but the code itself is different from the one in the book right now (some ORs should be ANDs I think).

**Comment by rxu18** [comment]
I see. Thanks!

**Comment by rxu18** [comment]
Both codes are incorrect: run the program on $0110$ and both return 1, when we expect 0. 
@dzhou22 your program is closer, and I think the line that is off is temp 4. Here, we want a>=c. If we change the line to `temp_4 = OR(X[0],temp_1)`, everything should work.
Making a PR right now.

**Comment by dzhou22** [comment]
Oh yeah, I see, thanks.

**Comment by boazbk** [comment]
Thanks so much to you both!

**Comment by maxgrozo** [comment]
At the end of the proof of Lemma 3.3, I believe you meant "AND(" rather than "OR(". 

Also, love the stuff on al-Khwarizmi; thanks for including all of it. It's a shame that the Persian word for "algorithm" uses the "transliterate" function to map his name from Persian to Arabic to Latin to English (I skip a bunch of historical steps here) to Persian rather than just calling it الخوارزمية like in Arabic.

Finally, your script for "solve_eq" would have benefitted from a final comment reading
# والله يعلم الأفضل
for completeness :)
