### ISSUE TITLE
Turing Machine definition (Definition 6.2)

### ISSUE THREAD

**Issue by evansuva** [boazbk/tcs#385]
There are a few subtleties in the definition of the Turing Machine (Definition 6.2) that might be confusing:

- The way the alphabet is defined suggests there can be symbols other than {0, 1} in the working alphabet, but the way M(x) is defined it ends with "the smallest integer such that 𝑇 [𝑚 + 1] ∉ {0, 1}". This means any other symbols after the last {0, 1} would not be included in the output. This might make sense if we required the output to be in {0, 1}*, but the way it is defined now still allows the output to contain the $\triangleright$ and $\varnothing$ symbols (and any other symbols added to the alphabet that occur before the last {0, 1}. A more conventional definition would be $m$ is the smallest integers such that for all $l > m, T[l] = \varnothing$.

- Another subtlety is that the way $M(x)$ is defined excludes $T[0]$, which makes sense if it is always the start-of-tape $\triangleright$ marker. But, nothing in the execution rules prevents this from being overwritten with another symbol (or disallows writing $\triangleright$s elsewhere). I'm not sure of a good solution to this and I like the simplicity of just having one alphabet and requiring these special symbols rather than more complex conventional definitions I've seen that need separate tape and input alphabets or other complications, but maybe there is a simpler definition that just includes the sequence of all the 0, 1 symbols in order on the tape, ignoring all other symbols, so ensures $M(x) \in {0, 1}^*$. Either that, or make $M(x)$ include all symbols from $T[0]$ up to the last non-$\varnothing$ symbol.

**Comment by boazbk** [comment]
Good points. Since throughout the book we always restricted attention to binary inputs and outputs, maybe the easiest thing is to define the output at the end to be the concatenation of all 0/1 symbols from the current head leftward

This also allows to output a single bit without having to travel all the way to the end, but ensures that we keep the invariant that we can’t output more bits than the number of steps we took.

**Comment by boazbk** [comment]
Made that edit - please take a look (already in the source - should compile shortly) and let me know what you think

**Comment by evansuva** [comment]
Yes, I like this definition a lot - it is simple and clear, and is also closer to Turing's historical model which would only print 0s and 1s on a separate output tape.

The only tweak I would suggest now is removing the "Stay" direction, which isn't included in most other definitions I've seen and I don't think it is useful in producing more compact machines in many cases.

**Comment by boazbk** [comment]
OK let me think about it - probably I would not be able to do it during the term anyway since it effects a number of figures that would have to be re-drawn.
I am trying to reconstruct why I put Stay there in the first place... I do think it's there in some of the online simulators. Maybe I did so because I anyway had two bits for the MODANDJMP in NANDTM so might as well have 4 options, and wanted to keep the close match between the two?
