### ISSUE TITLE
Error in Exercise 5.4

### ISSUE THREAD

**Issue by VarunVejalla** [boazbk/tcs#790]
The result in Exercise 5.4 doesn't hold when m is large in comparison to n. For example, let n=1 and m be large. Then for any function f:{0,1} to {0,1}^m, for each output f_k, there are four cases: f_k(0) = f_k(1) = 0, f_k(0) = 0 and f_k(1) = 1, f_k(0) = 1 and f_k(1) = 0, and f_k(0) = f_k(1) = 1. Each of these can be computed with at most three NAND gates, which means that 4*3 = 12 NAND gates would be sufficient to represent any function f since you could just map each of the earlier four cases to their appropriate indices (reusing the outputs of the earlier cases as needed). However the exercise implies that this should grow with m too.

-Varun Vejalla

**Comment by boazbk** [comment]
You are right. I think the bound is true if we require each output to be connected to a unique gate, since then the counting argument works, but otherwise it doesn't. The maximum amount of saving is $O(m)$ (more precisely $2m$) gates so the bound holds as long as $2m = o(\delta m 2^n/n)$ so it should work for every sufficiently large $n$, where $2^n \gg n$.

**Comment by boazbk** [comment]
Actually I think that the formal definition I used for circuits ([Definition 3.5](https://introtcs.org/public/lec_03_computation.html#boolean-circuits-a-formal-definition))  does require that every output correspond to a unique gate. However, to avoid confusion I will make the condition that $n$ is large enough and add a discussion of this issue to the foot note hint. Thanks!!
